### ISSUE TITLE
Server keep crashing

### ISSUE THREAD

**Issue by karam1ashqar** [facn5/CoffeeBros#44]
TypeError: Cannot read property 'address_id' of undefined
    at selectQueries.getPlacesByName (/home/karam/Desktop/FACN5/Team-Projects/Week06/Review/CoffeeBros/src/handlers.js:65:50)
    at databaseConnection.query (/home/karam/Desktop/FACN5/Team-Projects/Week06/Review/CoffeeBros/database/queries/selectquery.js:8:7)
    at Query.client.query (/home/karam/Desktop/FACN5/Team-Projects/Week06/Review/CoffeeBros/node_modules/pg-pool/index.js:300:18)
    at Query.handleReadyForQuery (/home/karam/Desktop/FACN5/Team-Projects/Week06/Review/CoffeeBros/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/home/karam/Desktop/FACN5/Team-Projects/Week06/Review/CoffeeBros/node_modules/pg/lib/client.js:215:19)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at TLSSocket.<anonymous> (/home/karam/Desktop/FACN5/Team-Projects/Week06/Review/CoffeeBros/node_modules/pg/lib/connection.js:125:12)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Bear-Coding** [comment]
It is because we still don't have validation for input.
